services:
  etg-db:
    image: 'postgres:14.11'
    container_name: 'etelegramDB'
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_USER=etg
      - POSTGRES_PASSWORD=purple
      - POSTGRES_DB=etgDB
    restart: always
    volumes:
      - nyos_db_data:/var/lib/postgresql/data

volumes:
  nyos_db_data: